=== Sebmaestro/antitowerdefence/src/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="levels">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="level" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="map" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="row" minOccurs="1" maxOccurs="10">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tile" minOccurs="0" maxOccurs="10">
                                                        <xs:complexType>
                                                            <xs:attribute name="type" type="xs:string"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name ="name" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Sebmaestro/antitowerdefence/src/resources/testLevel.xml
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<levels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
  <level>
=======
<levels>
  <level name="Level 1">
>>>>>>> mammabranch
    <map>
      <row>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Start"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Path"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
      </row>
      <row>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Grass"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Goal"/>
        <tile type="model.Tile.Towerzone"/>
        <tile type="model.Tile.Grass"/>
      </row>
    </map>
  </level>
</levels>
